version: 1.0.{build}

branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: Any CPU
build:
  verbosity: minimal
before_build:
  - nuget restore
artifacts:
- path: DeskEnv\bin\Release\DeskEnv.exe
  name: DeskEnv.exe
deploy:
- provider: GitHub
  auth_token:
    secure: +x5EgVVdmXkMqX8xb3svcNZNwQ/6SGsEJOwoSoK4HacN7ju+APPVjR5kQZS3bz2L
  artifact: DeskEnv.exe
  draft: true